spring:
  application:
    name: locadora-veiculos

server:
  port: 8083

logging:
  level:
    com.locadora: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
